== Site builder

This builds a static site for given Paneron RegistryKit based dataset.

Not production ready; currently under development.

Intended to be run as:

[source,bash]
----
npx @paneron/site-builder --outdir dist [--datadir path/to/register] [watch --serve]
----

More complete option overview:

[source,bash]
----
npx @paneron/site-builder \
  --outdir dist \
  [--debug | --verbose] \
  [--datadir path/to/register] \
  [--dataversion (git rev-parse --short HEAD)] \
  [--devextpath /path/to/local/extension] \
  [--forusername <username>] \
  [watch [--serve] [--watch-template] [--port 12345]]
----

It would:

* place site assets under `+outdir+`,
* generate data indices as required by site runtime and place them under
`+outdir+` where expected.

Uses Node 20.11.1.

=== Development

Tested on:

* Node 20.11.1

Note that build is handled by esbuild, while TSC is still used for
typechecking. Type errors shouldn’t be ignored, but a type error may
still result in a valid build (depends on specifics).

Important scripts:

* Root package’s `+build-self+` script compiles site builder
* site/spa’s `+clean-build+` script compiles front-end code
+
[IMPORTANT]
====
This repository uses Yarn PnP, but in `+loose+` mode for the sake of
`+spa+` package build script. Since ExtensionKit and RegistryKit import
packages that they list only in `+devDependencies+`, in strict mode
esbuild would fail with an
https://stackoverflow.com/questions/76015181/the-yarn-plugnplay-manifest-forbids-importing-xyz-here-because-its-not-list[error]
for every such import when bundling SPA for client-side.
====

===== Testing with local data

====== Requirements

$DATADIR::  path to Paneron dataset directory (must contain `panerondataset.yaml`)
$OUTDIR::  path to output directory.  Will be created by this tool if not exists.

====== Common steps

. Working from the repository root, build the site builder:
+
[source,console]
----
> yarn run build-self
> ls package.mjs
package.mjs
----

====== Building the site artifacts

[start=2]
. Run `./build-site.mjs` with the required parameters:
+
[source,console]
----
> ./build-site.mjs --datadir "$DATADIR" --outdir "$OUTDIR"
Fetch extension code from .../extension.js to $OUTDIR/extension.js: 863.576ms
Fetch package.json from .../package.json to $OUTDIR/package.json: 407.994ms
Fetch extension JS $OUTDIR: 1.283s
Scaffold site template from .../site/spa/dist into $OUTDIR: 3.027s
Fetch extension code from .../extension.js to $OUTDIR/extension.js: 178.606ms
Fetch package.json from .../package.json to $OUTDIR/package.json: 87.67ms
Importing site builder from .../site/spa/build-site.mjs: 84.967ms
Running site builder: 754.246ms
>
----

====== Serving site with local data

[start=2]
. Run `./build-site.mjs` with the required parameters, with the `watch --serve` option.
When done, press `Ctrl-C` to stop serving:
+
[source,console]
----
> ./build-site.mjs --datadir "$DATADIR" --outdir "$OUTDIR" watch --serve --port 8080
Fetch extension code from .../extension.js to $OUTDIR/extension.js: 863.576ms
Fetch package.json from .../package.json to $OUTDIR/package.json: 407.994ms
Fetch extension JS $OUTDIR: 1.283s
Scaffold site template from .../site/spa/dist into $OUTDIR: 3.027s
Fetch extension code from .../extension.js to $OUTDIR/extension.js: 178.606ms
Fetch package.json from .../package.json to $OUTDIR/package.json: 87.67ms
Importing site builder from .../site/spa/build-site.mjs: 84.967ms
Running site builder: 754.246ms
^C^C
>
----


==== Release

* Remember to run the important scripts before testing & publishing
* Run `+npm publish+` from the root (no need to change into a separate
“dist” dir)
